name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        platform:
          - iOS
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: mxcl/xcodebuild@v1
        with:
          platform: ${{ matrix.platform }}
          action: test
          scheme: SessionManager
          code-coverage: true
          upload-logs: always
